version: "3"
services:
  # # REDIS
  # redis:
  #   image: redis
  #   container_name: emotionfy-redis
  # EXPRESS: 5000
  api:
    build: 
      context: ./emotionfy-api
      dockerfile: Dockerfile.dev
    image: cabemo/emotionfy-api
    env_file: ./emotionfy-api/.env
    container_name: emotionfy-api
    volumes:
      - ./node_modules
  # CLIENT: 3000
  client:
    image: cabemo/emotionfy
    container_name: emotionfy
    build:
      context: ./emotionfy
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
    stdin_open: true
  # PYTHON: 8000
  pyapi:
    image: robtry/emotionapi
    container_name: emotionfy-python
    # build:
    #   context: ./emotion-recognition
    #   dockerfile: .
  # NGINX
  nginx:
    image: cabemo/emotionfy-nginx
    container_name: emotionfy-nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
    depends_on:
      - api
      - pyapi
      - client
